### ISSUE TITLE
Refactor pricing into a trait

### ISSUE THREAD

**Issue by rruckley** [rruckley/tmflib#70]
TMF648 has QuotePrice and TMF663 has CartPrice.

Both of these structures have similar requirements, including tax free and tax inc pricing and associated functions.

This should be refactored to pull this into a Trait that is then implemented by both structs.

Further tmflib-macro can  be updated to provide default implementation of the trait functions.

**Comment by rruckley** [comment]
@ignazio-castrogiovanni  Something worth looking at perhaps?

**Comment by ignazio-castrogiovanni** [comment]
I can't see TMF663 CartPrice in master. Is it still to be implemented? Where can I look at the specifics?

**Comment by rruckley** [comment]
> I can't see TMF663 CartPrice in master. Is it still to be implemented? Where can I look at the specifics?

It's still in a PR, I was working on conversion between ShoppingCart and a product order when I noticed the refactor.

**Comment by rruckley** [comment]
@ignazio-castrogiovanni  Happy to take you though my approach for this.
